[supervisord]
nodaemon=true

[program:api]
command=python /app/movie-sentiment-api/app.py
autostart=true
autorestart=true

[program:ml]
command=python /app/movie-sentiment-backend/app.py
autostart=true
autorestart=true
